import { useState, type FormEvent } from 'react';
import { ArrowRight, LoaderCircle } from 'lucide-react';
import { Logo } from './components';
import { api } from './lib';
import type { Session } from './types';
export default function Auth({onSession,registrationAllowed}:{onSession:(s:Session)=>void;registrationAllowed:boolean}) {
  const [register,setRegister]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const data=Object.fromEntries(new FormData(e.currentTarget));onSession(await api(register?'register':'login',data));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="auth-page"><aside className="auth-story"><Logo/><div><span className="eyebrow">TU EQUIPO. CADA MINUTO.</span><h1>El fútbol<br/>se juega<br/><em>en equipo.</em></h1><p>Tu plantilla, tus partidos y el tiempo que cada jugador deja en el campo.</p></div><span className="auth-bottom">HECHO PARA VIVIRLO DESDE LA BANDA <b>↗</b></span></aside><main className="auth-main"><div className="auth-form"><div className="auth-mark"><Logo small/></div><span className="eyebrow">BIENVENIDO AL VESTUARIO</span><h2>{register?'Aquí empieza tu equipo.':'Volvemos al campo.'}</h2><p>{register?'Crea tu cuenta y prepara la temporada.':'Entra para seguir sumando minutos.'}</p><form onSubmit={submit}>{register&&<><label className="field"><span>Tu nombre</span><input name="name" autoComplete="name" required maxLength={100} placeholder="Nombre del entrenador"/></label><label className="field"><span>Nombre de tu equipo</span><input name="teamName" required maxLength={100} placeholder="Ej. Sky Blue FC"/></label></>}<label className="field"><span>Correo electrónico</span><input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="tu@equipo.com"/></label><label className="field"><span>Contraseña</span><input name="password" type="password" autoComplete={register?'new-password':'current-password'} required minLength={10} maxLength={128} placeholder={register?'Al menos 10 caracteres':'Tu contraseña'}/></label>{error&&<div className="error-text" role="alert">{error}</div>}<button className="button dark full-width" disabled={busy}>{busy?<LoaderCircle size={18} className="spin"/>:null}{register?'Crear mi equipo':'Entrar al vestuario'}<ArrowRight size={18}/></button></form>{registrationAllowed&&<div className="auth-toggle">{register?'¿Ya tienes equipo?':'¿Primera temporada aquí?'}<button className="text-button" onClick={()=>{setRegister(!register);setError('');}}>{register?'Iniciar sesión':'Crear una cuenta'}</button></div>}</div><footer>minuto. <span>Cada minuto importa.</span></footer></main></div>;
}
