import { ArrowDownToLine, ArrowRight, CalendarDays, ChevronRight, Clock3, MapPin, Play, Plus, Users, Trophy } from 'lucide-react';
import type { Team } from './types';
import { Avatar, Crest, Empty, FixtureRow, Pitch } from './components';
import { dateLabel, timeLabel, totalFor, downloadCSV } from './lib';
export default function Dashboard({team,openMatch,navigate,newFixture}:{team:Team;openMatch:(id:string)=>void;navigate:(view:string)=>void;newFixture:()=>void}) {
  const {settings}=team;
  const matches=team.matches.filter(m=>m.season===settings.season);
  const next=matches.find(m=>['live','paused'].includes(m.status))??matches.filter(m=>m.status==='scheduled').sort((a,b)=>a.date.localeCompare(b.date))[0];
  const finished=matches.filter(m=>m.status==='finished');
  const players=team.players.filter(p=>!p.archived);
  const leaders=[...team.players].sort((a,b)=>totalFor(team,b.id)-totalFor(team,a.id)).filter(p=>totalFor(team,p.id)>0).slice(0,5);
  const wins=finished.filter(m=>(m.home?m.homeScore:m.awayScore)>(m.home?m.awayScore:m.homeScore)).length;
  function exportStats(){downloadCSV('minutos-temporada.csv',[['Jugador','Dorsal','Temporada','Minutos','Segundos totales'],...team.players.map(p=>[p.name,p.number,settings.season,Math.floor(totalFor(team,p.id)/60),Math.floor(totalFor(team,p.id))])]);}
  return <><div className="page-heading"><div><div className="eyebrow">TU EQUIPO. CADA MINUTO.</div><h1>Vamos a por el próximo.</h1><p>Todo listo para lo que pasa dentro del campo.</p></div><button className="button secondary" onClick={exportStats}><ArrowDownToLine size={17}/> Exportar minutos</button></div>
    <section className="stat-grid"><div className="stat-card"><div><span>Jugadores en plantilla</span><Users size={18}/></div><strong>{players.length.toString().padStart(2,'0')}</strong><small>Una plantilla, un equipo</small></div><div className="stat-card"><div><span>Partidos jugados</span><CalendarDays size={18}/></div><strong>{finished.length.toString().padStart(2,'0')}<em>/ {matches.length.toString().padStart(2,'0')}</em></strong><small>Temporada {settings.season}</small></div><div className="stat-card"><div><span>Minutos de juego</span><Clock3 size={18}/></div><strong>{Math.floor(finished.reduce((n,m)=>n+m.elapsedSeconds,0)) / 60 | 0}<em>min</em></strong><small>Tiempo de partidos finalizados</small></div><div className="stat-card"><div><span>Victorias</span><Trophy size={18}/></div><strong>{wins.toString().padStart(2,'0')}</strong><small>{finished.length?`${Math.round(wins/finished.length*100)}% de los partidos jugados`:'La temporada está por escribir'}</small></div></section>
    <div className="dashboard-grid"><section className="next-match"><div className="section-top"><span className="eyebrow">{next?.status==='live'?'PARTIDO EN DIRECTO':'PRÓXIMO PARTIDO'}</span><span className="light-tag">{next?`JORNADA ${next.round}`:'TEMPORADA '+settings.season}</span></div>{next?<><div className="match-versus"><div><Crest name={settings.name} large/><h3>{settings.name}</h3><small>{next.home?'LOCAL':'VISITANTE'}</small></div><div className="versus">{['live','paused'].includes(next.status)?`${next.home?next.homeScore:next.awayScore} : ${next.home?next.awayScore:next.homeScore}`:'VS'}<span>{dateLabel(next.date,{weekday:'short',day:'numeric',month:'short'})}</span><b>{timeLabel(next.date)}</b></div><div><Crest name={next.opponent} opponent large/><h3>{next.opponent}</h3><small>{next.home?'VISITANTE':'LOCAL'}</small></div></div><div className="match-footer"><span><MapPin size={15}/>{next.venue||'Campo por confirmar'}</span><button className="button dark" onClick={()=>openMatch(next.id)}><Play size={16} fill="currentColor"/>{next.status==='scheduled'?'Preparar partido':'Ir al partido'}<ArrowRight size={17}/></button></div></>:<div className="next-empty"><Trophy size={44}/><h2>El próximo partido empieza aquí.</h2><button className="button dark" onClick={newFixture}><Plus size={18}/> Añadir partido</button></div>}</section>
    <section className="panel calendar-panel"><div className="panel-title"><h2>Calendario</h2><button className="text-button" onClick={()=>navigate('calendar')}>Ver todo<ChevronRight size={16}/></button></div><div className="mini-label">{settings.league}</div>{matches.length?matches.filter(m=>m.status!=='finished').sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3).map(m=><FixtureRow key={m.id} match={m} team={team} onClick={()=>openMatch(m.id)}/>):<Empty title="Tu liga, al día" detail="Añade el calendario de la temporada."/>}<button className="add-fixture" onClick={newFixture}><Plus size={16}/> Añadir partido</button></section>
    <section className="panel minutes-panel"><div className="panel-title"><div><h2>Cada minuto cuenta</h2><p>Los que más tiempo llevan en el campo.</p></div><button className="text-button" onClick={()=>navigate('stats')}>Estadísticas<ChevronRight size={16}/></button></div>{leaders.length?<div className="leader-list"><div className="leader-header"><span>JUGADOR</span><span>MINUTOS JUGADOS</span></div>{leaders.map((p,i)=><div className="leader" key={p.id}><span className="rank">0{i+1}</span><Avatar player={p}/><div className="leader-name"><strong>{p.name}</strong><span>{p.position} <b>·</b> Dorsal {p.number}</span></div><div className="leader-bar"><span style={{width:`${totalFor(team,p.id)/Math.max(1,totalFor(team,leaders[0].id))*100}%`}}/></div><strong className="leader-total">{Math.floor(totalFor(team,p.id)/60)}<span> min</span></strong></div>)}</div>:<Empty title="El primer minuto es el comienzo" detail="Los minutos aparecerán aquí al finalizar un partido."/>}</section>
    <section className="squad-panel"><div className="panel-title"><div><span className="eyebrow">JUNTOS EN EL CAMPO</span><h2>Un equipo.<br/>Muchas ganas.</h2></div><span className="squad-number">{settings.playersOnField}</span></div><Pitch players={players.filter(p=>next?.lineup.includes(p.id))} compact/><button className="button squad-button" onClick={()=>navigate('players')}>Ver mi plantilla <ArrowRight size={18}/></button></section></div>
    <div className="page-foot"><span>EL FÚTBOL SE JUEGA EN EQUIPO.</span><LogoText/></div></>;
}
function LogoText(){return <span>cada minuto importa <b>↗</b></span>;}
