import { useState, type FormEvent } from 'react';
import Papa from 'papaparse';
import { ArrowDownToLine, Check, LoaderCircle, Pencil, Plus, Shield, Trash2, Trophy, Upload } from 'lucide-react';
import { Crest, ImageField, Modal } from './components';
import type { League, Match, Player, Settings, Team, Workspace } from './types';
import { age, positions, downloadCSV } from './lib';
export type Command = (type:string,payload:Record<string,unknown>)=>Promise<boolean>;
function Submit({busy,label='Guardar'}:{busy:boolean;label?:string}) {return <button className="button" type="submit" disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>} {label}</button>;}
export function PlayerForm({player,command,onClose,busy}:{player?:Player;command:Command;onClose:()=>void;busy:boolean}) {
  const [name,setName]=useState(player?.name??''),[number,setNumber]=useState(player?.number.toString()??''),[position,setPosition]=useState(player?.position??'MED'),[birthdate,setBirthdate]=useState(player?.birthdate??''),[photoId,setPhotoId]=useState<string|null>(player?.photoId??null);
  async function submit(e:FormEvent){e.preventDefault();if(await command('player.save',{id:player?.id,name,number:Number(number),position,birthdate:birthdate||null,photoId}))onClose();}
  const years=age(birthdate||null);
  return <Modal title={player?'Editar jugador':'Un nuevo fichaje'} onClose={onClose}><form onSubmit={submit}><p className="form-note">Versión para jugadores adultos. Informa al jugador antes de añadirlo. Foto y fecha de nacimiento son opcionales; añade solo los datos necesarios.</p><ImageField label="Foto del jugador (opcional)" value={photoId} onChange={setPhotoId} shape="circle" disabled={busy}/><div className="form-grid"><label className="field full"><span>Nombre o alias</span><input autoFocus required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. David Santana"/></label><label className="field"><span>Dorsal</span><input type="number" inputMode="numeric" required min={0} max={99} value={number} onChange={e=>setNumber(e.target.value)} placeholder="8"/></label><label className="field"><span>Posición</span><select value={position} onChange={e=>setPosition(e.target.value as Player['position'])}>{Object.entries(positions).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label className="field full"><span>Fecha de nacimiento (opcional){years!==null?` · ${years} años`:''}</span><input type="date" value={birthdate} max={new Date().toISOString().slice(0,10)} onChange={e=>setBirthdate(e.target.value)}/></label></div><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><Submit busy={busy} label={player?'Guardar cambios':'Añadir jugador'}/></div></form></Modal>;
}
function localDateValue(date:Date){return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function FixtureForm({match,team,leagues,command,onClose,busy}:{match?:Match;team:Team;leagues:League[];command:Command;onClose:()=>void;busy:boolean}) {
  const [opponent,setOpponent]=useState(match?.opponent??''),[date,setDate]=useState(localDateValue(match?new Date(match.date):new Date())),[venue,setVenue]=useState(match?.venue??''),[round,setRound]=useState(match?.round??team.matches.filter(m=>m.season===team.settings.season).reduce((n,m)=>Math.max(n,m.round),0)+1),[home,setHome]=useState(match?.home??true),[leagueId,setLeagueId]=useState(match?.leagueId??leagues[0]?.id??'');
  async function submit(e:FormEvent){e.preventDefault();if(await command('fixture.save',{id:match?.id,opponent,date:new Date(date).toISOString(),venue,round,home,season:match?.season??team.settings.season,leagueId:leagueId||null}))onClose();}
  return <Modal title={match?'Editar partido':'Añadir partido'} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><label className="field full"><span>Equipo rival</span><input autoFocus required maxLength={100} value={opponent} onChange={e=>setOpponent(e.target.value)} placeholder="Ej. CD Atlántico"/></label><label className="field full"><span>Fecha y hora local</span><input required type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>Jornada</span><input type="number" required min={1} max={100} value={round} onChange={e=>setRound(Number(e.target.value))}/></label><label className="field"><span>Jugamos como</span><select value={home?'home':'away'} onChange={e=>setHome(e.target.value==='home')}><option value="home">Local</option><option value="away">Visitante</option></select></label>{leagues.length>0&&<label className="field full"><span>Competición</span><select value={leagueId} onChange={e=>setLeagueId(e.target.value)}><option value="">Sin competición</option>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}<label className="field full"><span>Campo</span><input maxLength={120} value={venue} onChange={e=>setVenue(e.target.value)} placeholder="Campo municipal"/></label></div><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><Submit busy={busy}/></div></form></Modal>;
}
export function ImportFixtures({team,command,onClose,busy}:{team:Team;command:Command;onClose:()=>void;busy:boolean}) {
  const [rows,setRows]=useState<Record<string,unknown>[]>([]),[error,setError]=useState(''),[filename,setFilename]=useState('');
  function load(file:File|undefined){if(!file)return;setRows([]);setError('');setFilename(file.name);if(file.size>200000){setError('El archivo debe pesar menos de 200 KB.');return;}
    Papa.parse<Record<string,string>>(file,{header:true,skipEmptyLines:'greedy',transformHeader:h=>h.trim().toLowerCase(),complete:result=>{
      try {if(result.errors.length)throw Error('No se puede leer el CSV. Usa la plantilla de ejemplo.');if(result.data.length>100||!result.data.length)throw Error('El archivo debe contener entre 1 y 100 partidos.');
        setRows(result.data.map((r,i)=>{const number=i+2;const date=new Date(`${r.fecha}T${r.hora||'18:00'}:00`); if(!/^\d{4}-\d{2}-\d{2}$/.test(r.fecha||'')||!/^\d{2}:\d{2}$/.test(r.hora||'18:00')||!Number.isFinite(date.getTime())||localDateValue(date).slice(0,10)!==r.fecha||!r.rival?.trim()||!['si','sí','no'].includes(r.local?.trim().toLowerCase())||!Number.isInteger(Number(r.jornada))||Number(r.jornada)<1||Number(r.jornada)>100)throw Error(`Revisa la fila ${number}: fecha, hora, rival, local (sí/no) y jornada.`);return {opponent:r.rival.trim(),date:date.toISOString(),home:r.local.trim().toLowerCase()!=='no',round:Number(r.jornada),venue:r.campo?.trim()||'',season:team.settings.season,leagueId:null};}));
      }catch(e){setRows([]);setError((e as Error).message);}
    },error:()=>setError('No se puede abrir el archivo.')});
  }
  return <Modal title="Importar calendario" onClose={onClose} wide><p className="form-note">Carga los partidos de la temporada {team.settings.season}. Las fechas y horas se interpretan en la zona horaria de este dispositivo. Los partidos se añaden al calendario actual.</p><button className="button secondary template-button" onClick={()=>downloadCSV('plantilla-calendario.csv',[['fecha','hora','rival','local','jornada','campo'],['2026-09-20','18:00','CD Atlántico','sí',1,'Campo municipal']])}><ArrowDownToLine size={17}/> Descargar plantilla CSV</button><label className="field full"><span>Archivo CSV</span><input type="file" accept=".csv,text/csv" onChange={e=>load(e.target.files?.[0])}/></label>{error&&<div className="error-text">{error}</div>}{rows.length>0&&<div className="import-preview"><strong>{rows.length} partidos listos para añadir</strong><span>{filename}</span>{rows.slice(0,4).map((r,i)=><p key={i}>J{String(r.round)} · {String(r.opponent)} · {new Date(String(r.date)).toLocaleDateString('es-ES')}</p>)}{rows.length>4&&<p>Y {rows.length-4} más</p>}</div>}<div className="form-actions"><button className="button secondary" onClick={onClose}>Cancelar</button><button className="button" disabled={busy||!rows.length} onClick={async()=>{if(await command('fixture.import',{fixtures:rows}))onClose();}}><Upload size={17}/> Importar {rows.length||''} partidos</button></div></Modal>;
}
function LeagueForm({league,command,onClose,busy}:{league?:League;command:Command;onClose:()=>void;busy:boolean}) {
  const [name,setName]=useState(league?.name??''),[season,setSeason]=useState(league?.season??''),[color,setColor]=useState(league?.color??'#8ac9eb');
  async function submit(e:FormEvent){e.preventDefault();if(await command('league.save',{id:league?.id,name,season,color}))onClose();}
  return <Modal title={league?'Editar liga':'Nueva liga o competición'} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><label className="field full"><span>Nombre</span><input autoFocus required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Liga Municipal Fútbol 7"/></label><label className="field"><span>Temporada</span><input required maxLength={100} value={season} onChange={e=>setSeason(e.target.value)} placeholder="2026/27"/></label><label className="field"><span>Color</span><input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label></div><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><Submit busy={busy} label={league?'Guardar cambios':'Crear liga'}/></div></form></Modal>;
}
export function LeagueManager({workspace,command,busy}:{workspace:Workspace;command:Command;busy:boolean}) {
  const [dialog,setDialog]=useState<{kind:'edit';league?:League}|{kind:'delete';league:League}|null>(null);
  return <div className="panel league-panel"><div className="settings-section-title"><Trophy size={22}/><div><h2>Ligas y competiciones</h2><p>Se comparten entre todos tus equipos, aunque jueguen en ligas distintas.</p></div><button className="button secondary small" onClick={()=>setDialog({kind:'edit'})}><Plus size={16}/> Nueva liga</button></div>{workspace.leagues.length?<div className="league-list">{workspace.leagues.map(l=><div className="league-row" key={l.id}><span className="league-swatch" style={{background:l.color}}/><div className="league-row-name"><strong>{l.name}</strong><span>{l.season} · {workspace.teams.filter(t=>t.settings.leagueIds.includes(l.id)).length} equipos</span></div><div className="button-group"><button className="icon-button" aria-label={`Editar ${l.name}`} onClick={()=>setDialog({kind:'edit',league:l})}><Pencil size={15}/></button><button className="icon-button" aria-label={`Eliminar ${l.name}`} onClick={()=>setDialog({kind:'delete',league:l})}><Trash2 size={15}/></button></div></div>)}</div>:<p className="form-note">Todavía no has creado ninguna liga. Crea la primera para organizar tu calendario por competición.</p>}
    {dialog?.kind==='edit'&&<LeagueForm league={dialog.league} command={command} busy={busy} onClose={()=>setDialog(null)}/>}
    {dialog?.kind==='delete'&&<Modal title="Eliminar liga" onClose={()=>setDialog(null)}><p className="form-note">Se eliminará «{dialog.league.name}». Los equipos y partidos que la usaban dejarán de tener competición asignada.</p><div className="form-actions"><button className="button secondary" onClick={()=>setDialog(null)}>Cancelar</button><button className="button danger" disabled={busy} onClick={async()=>{if(await command('league.delete',{id:dialog.league.id}))setDialog(null);}}>Eliminar liga</button></div></Modal>}
  </div>;
}
export function TeamSwitcherModal({workspace,command,onClose,busy}:{workspace:Workspace;command:Command;onClose:()=>void;busy:boolean}) {
  const [name,setName]=useState(''),[pendingDelete,setPendingDelete]=useState<string|null>(null);
  return <Modal title="Tus equipos" onClose={onClose}><div className="team-list">{workspace.teams.map(t=>{const active=t.id===workspace.activeTeamId;return <div key={t.id} className={`team-list-row ${active?'active':''}`}><Crest name={t.settings.name} crestId={t.settings.crestId} colors={t.settings.colors}/><div className="team-list-name"><strong>{t.settings.name}</strong><span>{t.settings.season}</span></div>{pendingDelete===t.id?<div className="button-group"><button type="button" className="text-button" onClick={()=>setPendingDelete(null)}>Cancelar</button><button className="button danger small" disabled={busy} onClick={async()=>{if(await command('team.delete',{id:t.id}))setPendingDelete(null);}}>Eliminar</button></div>:<div className="button-group">{active?<span className="status-label live">Activo</span>:<button className="button secondary small" disabled={busy} onClick={async()=>{if(await command('team.select',{id:t.id}))onClose();}}>Seleccionar</button>}{workspace.teams.length>1&&<button className="icon-button" aria-label={`Eliminar ${t.settings.name}`} disabled={busy} onClick={()=>setPendingDelete(t.id)}><Trash2 size={16}/></button>}</div>}</div>;})}</div>
    <form className="team-create-form" onSubmit={async e=>{e.preventDefault();const value=name.trim();if(!value)return;if(await command('team.create',{name:value})){setName('');onClose();}}}><label className="field full"><span>Nuevo equipo</span><input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Juvenil B"/></label><div className="form-actions"><Submit busy={busy} label="Crear equipo"/></div></form>
  </Modal>;
}
export function SettingsPage({workspace,team,command,busy,logout}:{workspace:Workspace;team:Team;command:Command;busy:boolean;logout:()=>void}) {
  const [value,setValue]=useState<Settings>(team.settings);
  const update=(key:keyof Settings,next:unknown)=>setValue(v=>({...v,[key]:next}));
  const toggleLeague=(id:string)=>update('leagueIds',value.leagueIds.includes(id)?value.leagueIds.filter(l=>l!==id):[...value.leagueIds,id]);
  return <><div className="page-heading"><div><div className="eyebrow">LA IDENTIDAD DEL CLUB</div><h1>Tu equipo, tus reglas.</h1><p>Prepara la temporada a tu medida.</p></div></div><form className="panel settings-panel" onSubmit={async e=>{e.preventDefault();await command('settings',value as unknown as Record<string,unknown>);}}><div className="settings-section-title"><Shield size={24}/><div><h2>Información del equipo</h2><p>Estos datos aparecen en tu calendario y tus estadísticas.</p></div></div><div className="form-grid"><label className="field full"><span>Nombre del equipo</span><input required maxLength={100} value={value.name} onChange={e=>update('name',e.target.value)}/></label><label className="field"><span>Temporada activa</span><input required maxLength={100} value={value.season} onChange={e=>update('season',e.target.value)} placeholder="2026/27"/></label><label className="field"><span>Modalidad</span><select value={value.playersOnField} onChange={e=>update('playersOnField',Number(e.target.value))}>{[5,7,8,11].map(n=><option key={n} value={n}>Fútbol {n}</option>)}</select></label><label className="field"><span>Duración prevista (minutos)</span><input required type="number" min={10} max={180} value={value.matchMinutes} onChange={e=>update('matchMinutes',Number(e.target.value))}/></label><label className="check-field"><input type="checkbox" checked={value.allowReentry} onChange={e=>update('allowReentry',e.target.checked)}/> Permitir que un jugador sustituido vuelva a entrar</label><div className="field full"><span>Competiciones</span>{workspace.leagues.length?<div className="league-checks">{workspace.leagues.map(l=><label key={l.id} className="league-check"><input type="checkbox" checked={value.leagueIds.includes(l.id)} onChange={()=>toggleLeague(l.id)}/><span className="league-swatch" style={{background:l.color}}/>{l.name}</label>)}</div>:<p className="form-note">Crea una liga más abajo para asignarla a este equipo.</p>}</div></div><p className="form-note settings-note">La duración es orientativa: el cronómetro continúa hasta que lo detengas. Cambiar la temporada conserva los partidos anteriores y filtra el resumen de minutos.</p>
    <div className="settings-section-title branding-title"><div className="crest-preview"><Crest name={value.name} crestId={value.crestId} colors={value.colors} large/></div><div><h2>Escudo y colores</h2><p>Se aplican al escudo del equipo y a las camisetas de la plantilla.</p></div></div><div className="branding-grid"><ImageField label="Escudo del equipo" value={value.crestId} onChange={id=>update('crestId',id)} disabled={busy}/><div className="color-fields"><label className="field"><span>Color principal</span><input type="color" value={value.colors.primary} onChange={e=>update('colors',{...value.colors,primary:e.target.value})}/></label><label className="field"><span>Color secundario</span><input type="color" value={value.colors.secondary} onChange={e=>update('colors',{...value.colors,secondary:e.target.value})}/></label></div></div>
    <div className="form-actions"><Submit busy={busy} label="Guardar configuración"/></div></form>
    <LeagueManager workspace={workspace} command={command} busy={busy}/>
    <div className="account-panel"><p>Para usar tu equipo en otro iPad, inicia sesión con la misma cuenta.</p><button className="text-button" onClick={logout}>Cerrar sesión</button></div></>;
}
