import { useState } from 'react';
import { ArrowDownToLine, ArrowRight, CalendarDays, Clock3, Pencil, Plus, Search, Trash2, Upload, UserRoundX, Users } from 'lucide-react';
import { Avatar, Crest, Empty } from './components';
import type { Match, Player, Team } from './types';
import { dateLabel, downloadCSV, positions, secondsFor, timeLabel, totalFor } from './lib';
export function PlayersPage({team,add,edit,archive}:{team:Team;add:()=>void;edit:(p:Player)=>void;archive:(p:Player)=>void}) {
  const [search,setSearch]=useState(''),[position,setPosition]=useState('all');
  const players=team.players.filter(p=>!p.archived&&`${p.name} ${p.number}`.toLowerCase().includes(search.toLowerCase())&&(position==='all'||p.position===position)).sort((a,b)=>a.number-b.number);
  return <><div className="page-heading"><div><div className="eyebrow">LOS COLORES QUE NOS UNEN</div><h1>La plantilla.</h1><p>{team.players.filter(p=>!p.archived).length} jugadores. Un mismo escudo.</p></div><button className="button dark" onClick={add}><Plus size={18}/> Añadir jugador</button></div><div className="toolbar"><label className="search"><Search size={18}/><input aria-label="Buscar jugador" placeholder="Buscar nombre o dorsal…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="segmented">{[['all','Todos'],...Object.entries(positions)].map(([key,label])=><button key={key} className={position===key?'active':''} onClick={()=>setPosition(key)}>{label}</button>)}</div></div>{players.length?<div className="roster-grid">{players.map(p=><article className="player-card" key={p.id}><div className="player-card-top"><span className={`position-label pos-${p.position}`}>{positions[p.position]}</span><div className="button-group"><button className="icon-button" aria-label={`Editar ${p.name}`} onClick={()=>edit(p)}><Pencil size={16}/></button><button className="icon-button" aria-label={`Archivar ${p.name}`} onClick={()=>archive(p)}><UserRoundX size={16}/></button></div></div><div className="jersey-number">{p.number.toString().padStart(2,'0')}</div><h2>{p.name}</h2><div className="player-card-bottom"><span><Clock3 size={14}/><b>{Math.floor(totalFor(team,p.id)/60)}</b> min</span><span>{team.matches.filter(m=>m.status==='finished'&&m.season===team.settings.season&&m.stints.some(s=>s.playerId===p.id)).length} partidos</span></div></article>)}</div>:<div className="panel"><Empty title={search||position!=='all'?'No encontramos ese jugador':'Tu equipo empieza con sus jugadores'} detail={search||position!=='all'?'Prueba otro nombre, dorsal o posición.':'Añade nombres, dorsales y posiciones para preparar la alineación.'} action={!search&&position==='all'&&<button className="button" onClick={add}><Plus size={18}/> Añadir primer jugador</button>}/></div>}</>;
}
export function CalendarPage({team,add,importCSV,open,edit,remove}:{team:Team;add:()=>void;importCSV:()=>void;open:(id:string)=>void;edit:(m:Match)=>void;remove:(m:Match)=>void}) {
  const [filter,setFilter]=useState('upcoming');
  const matches=team.matches.filter(m=>m.season===team.settings.season&&(filter==='all'||(filter==='finished'?m.status==='finished':m.status!=='finished'))).sort((a,b)=>filter==='finished'?b.date.localeCompare(a.date):a.date.localeCompare(b.date));
  return <><div className="page-heading"><div><div className="eyebrow">EL CAMINO DE LA TEMPORADA</div><h1>Partido a partido.</h1><p>{team.settings.league} · {team.settings.season}</p></div><div className="button-group"><button className="button secondary" onClick={importCSV}><Upload size={17}/> Importar CSV</button><button className="button dark" onClick={add}><Plus size={18}/> Añadir partido</button></div></div><div className="toolbar"><div className="segmented">{[['upcoming','Próximos partidos'],['finished','Finalizados'],['all','Todos']].map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div><span className="result-count">{matches.length} partidos</span></div>{matches.length?<div className="calendar-list">{matches.map(m=><article className="calendar-match" key={m.id}><div className="calendar-meta"><span>JORNADA {m.round}</span><span className={`status-label ${m.status}`}>{({scheduled:'Programado',live:'En directo',paused:'En pausa',finished:'Finalizado'})[m.status]}</span></div><div className="calendar-match-content"><div className="calendar-match-date"><strong>{dateLabel(m.date,{day:'numeric',month:'short'})}</strong><span>{dateLabel(m.date,{weekday:'long'})} · {timeLabel(m.date)}</span></div><div className="calendar-match-teams"><Crest name={m.home?team.settings.name:m.opponent} opponent={!m.home}/><strong>{m.home?team.settings.name:m.opponent}</strong><span className="calendar-score">{m.status==='scheduled'?'vs':`${m.homeScore} — ${m.awayScore}`}</span><strong>{m.home?m.opponent:team.settings.name}</strong><Crest name={m.home?m.opponent:team.settings.name} opponent={m.home}/></div><button className="button secondary small" onClick={()=>open(m.id)}>{m.status==='finished'?'Ver resumen':m.status==='scheduled'?'Preparar':'Abrir directo'}<ArrowRight size={16}/></button></div><div className="calendar-match-bottom"><span>{m.venue||'Campo por confirmar'} · {m.home?'Local':'Visitante'}</span>{m.status==='scheduled'&&<div className="button-group"><button className="text-button" onClick={()=>edit(m)}><Pencil size={13}/> Editar</button><button className="icon-button" aria-label={`Borrar partido contra ${m.opponent}`} onClick={()=>remove(m)}><Trash2 size={14}/></button></div>}</div></article>)}</div>:<div className="panel"><Empty title={filter==='finished'?'La temporada está en juego':'El calendario espera al equipo'} detail={filter==='finished'?'Los partidos que finalices aparecerán aquí con su resultado.':'Añade los próximos encuentros o importa el calendario completo en CSV.'} action={filter!=='finished'&&<button className="button" onClick={add}><Plus size={18}/> Añadir partido</button>}/></div>}</>;
}
export function StatsPage({team}:{team:Team}) {
  const seasons=[...new Set([team.settings.season,...team.matches.map(m=>m.season)])].sort().reverse();
  const [season,setSeason]=useState(team.settings.season),[search,setSearch]=useState('');
  const finished=team.matches.filter(m=>m.status==='finished'&&m.season===season);
  const data=team.players.map(p=>{const seconds=finished.reduce((n,m)=>n+secondsFor(m,p.id,0),0);const played=finished.filter(m=>m.stints.some(s=>s.playerId===p.id));return {...p,seconds,appearances:played.length,starts:played.filter(m=>m.lineup.includes(p.id)).length};}).filter(p=>`${p.name} ${p.number}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.seconds-a.seconds);
  const time=finished.reduce((n,m)=>n+m.elapsedSeconds,0);
  return <><div className="page-heading"><div><div className="eyebrow">EL ESFUERZO, EN NÚMEROS</div><h1>Cada minuto cuenta.</h1><p>Minutos acumulados de los partidos finalizados.</p></div><button className="button secondary" onClick={()=>downloadCSV(`minutos-${season.replace('/','-')}.csv`,[['Jugador','Dorsal','Posición','Temporada','Partidos','Titularidades','Minutos','Segundos totales'],...data.map(p=>[p.name,p.number,positions[p.position],season,p.appearances,p.starts,Math.floor(p.seconds/60),Math.floor(p.seconds)])])}><ArrowDownToLine size={17}/> Exportar CSV</button></div><div className="toolbar"><label className="search"><Search size={18}/><input aria-label="Buscar en estadísticas" placeholder="Buscar jugador…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="season-select">Temporada<select aria-label="Temporada de estadísticas" value={season} onChange={e=>setSeason(e.target.value)}>{seasons.map(s=><option key={s}>{s}</option>)}</select></label></div><div className="panel stats-panel"><div className="table-scroll"><table className="data-table"><thead><tr><th>Jugador</th><th>Partidos</th><th>Titular</th><th>Minutos</th><th>Media / partido</th><th>Participación</th></tr></thead><tbody>{data.map((p,i)=><tr key={p.id}><td><div className="table-player"><span className="rank">{(i+1).toString().padStart(2,'0')}</span><Avatar player={p}/><div><strong>{p.name}</strong><span>{positions[p.position]}{p.archived?' · Archivado':''}</span></div></div></td><td>{p.appearances}</td><td>{p.starts}</td><td><strong>{Math.floor(p.seconds/60)}<small> min</small></strong></td><td>{p.appearances?(p.seconds/60/p.appearances).toFixed(1):'0'}<small> min</small></td><td><div className="participation"><span><i style={{width:`${time?p.seconds/time*100:0}%`}}/></span><b>{time?Math.round(p.seconds/time*100):0}%</b></div></td></tr>)}</tbody></table></div>{!data.length&&<Empty title="Todavía no hay estadísticas" detail="Añade jugadores y finaliza tu primer partido para empezar a sumar."/>}<div className="stats-note"><Clock3 size={16}/><span>{finished.length} partidos finalizados · {Math.floor(time/60)} minutos de juego. Se suman los segundos exactos antes de mostrar minutos completos.</span></div></div></>;
}
